server:
  port: 8580

spring:
  application:
    name: consumer-8580
  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
  instance:
    metadata-map:
      cluster: group2 #自定义eureka元数据


feign:
  client:
    config:
      default:
        #指定Feign客户端连接提供者的超时时限
        connectTimeout: 5000
        #指定Feign客户端连接上提供者后，向提供者进行提供请求，从提交时刻开始，到接受响应，这个时段的超时时限
        readTimeout: 5000
  #开始Feign对Hystrix的支持
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000

# 开启actuator的hystrix.stream监控终端
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream




